//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Panel
{
    public partial class PanelDefault
    {
        /// <summary>
        /// phProyectos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phProyectos;

        /// <summary>
        /// rptProyectos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptProyectos;

        /// <summary>
        /// phProyectosVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phProyectosVacio;
    }
}
