//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Panel
{
    public partial class Perfil
    {
        /// <summary>
        /// phOk control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phOk;

        /// <summary>
        /// litOk control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOk;

        /// <summary>
        /// phError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// fuFoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuFoto;

        /// <summary>
        /// txtNombres control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombres;

        /// <summary>
        /// txtApellidos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellidos;

        /// <summary>
        /// ddlCargo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCargo;

        /// <summary>
        /// txtPartido control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPartido;

        /// <summary>
        /// ddlDepartamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartamento;

        /// <summary>
        /// txtMunicipio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMunicipio;

        /// <summary>
        /// txtTitular control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitular;

        /// <summary>
        /// txtBiografia control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBiografia;

        /// <summary>
        /// txtProfesional control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtProfesional;

        /// <summary>
        /// txtCandidatura control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCandidatura;

        /// <summary>
        /// txtCorreo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;

        /// <summary>
        /// txtTelefono control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        /// <summary>
        /// txtSitio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSitio;

        /// <summary>
        /// txtFacebook control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFacebook;

        /// <summary>
        /// txtX control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtX;

        /// <summary>
        /// txtInstagram control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtInstagram;

        /// <summary>
        /// btnGuardar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
