//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Panel
{
    public partial class Proyectos
    {
        /// <summary>
        /// phLista control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        /// <summary>
        /// txtBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>
        /// ddlCategoria control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;

        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>
        /// rptProyectos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptProyectos;

        /// <summary>
        /// phVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
