//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Panel
{
    public partial class Proyecto
    {
        /// <summary>
        /// phOk control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phOk;

        /// <summary>
        /// litOk control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litOk;

        /// <summary>
        /// phError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// txtNombre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>
        /// txtDescripcion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        /// <summary>
        /// txtProblema control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtProblema;

        /// <summary>
        /// txtObjetivo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtObjetivo;

        /// <summary>
        /// txtBeneficiarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBeneficiarios;

        /// <summary>
        /// ddlCategoria control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;

        /// <summary>
        /// ddlEstado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>
        /// txtUbicacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUbicacion;

        /// <summary>
        /// txtPeriodo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPeriodo;

        /// <summary>
        /// fuImagen control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuImagen;

        /// <summary>
        /// txtAdicional control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAdicional;

        /// <summary>
        /// btnGuardar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
