//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Panel
{
    public partial class Publicaciones
    {
        /// <summary>
        /// phLista control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        /// <summary>
        /// rptPublicaciones control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPublicaciones;

        /// <summary>
        /// phVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
