//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Controles
{
    public partial class EncuestaCard
    {
        /// <summary>
        /// rptOpciones control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptOpciones;

        /// <summary>
        /// phAviso control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl phAviso;

        /// <summary>
        /// litAviso control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAviso;

        /// <summary>
        /// litPie control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPie;
    }
}
