//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Controles
{
    public partial class PropuestaCard
    {
        /// <summary>
        /// inter control.
        /// </summary>
        protected global::frontend.Controles.Interaccion inter;
    }
}
