//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Controles
{
    public partial class PublicacionCard
    {
        /// <summary>
        /// inter control.
        /// </summary>
        protected global::frontend.Controles.Interaccion inter;

        /// <summary>
        /// phComentarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phComentarios;

        /// <summary>
        /// coments control.
        /// </summary>
        protected global::frontend.Controles.Comentarios coments;
    }
}
