//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{
    public partial class Campanas
    {
        /// <summary>phMensaje control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        /// <summary>phForm control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phForm;

        /// <summary>txtNombre control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>txtInicio control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtInicio;

        /// <summary>txtEleccion control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEleccion;

        /// <summary>ddlEstado control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>txtAlcance control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtAlcance;

        /// <summary>txtResumen control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtResumen;

        /// <summary>txtDescripcion control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        /// <summary>chkActual control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActual;

        /// <summary>btnGuardar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>btnCancelar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>btnNuevo control.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>phLista control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        /// <summary>rptCampanas control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptCampanas;

        /// <summary>phVacio control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
