//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{
    public partial class Candidatos
    {
        /// <summary>phMensaje control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        /// <summary>phForm control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phForm;

        /// <summary>txtNombres control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombres;

        /// <summary>txtApellidos control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellidos;

        /// <summary>ddlCampana control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCampana;

        /// <summary>ddlCargo control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCargo;

        /// <summary>ddlPartido control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPartido;

        /// <summary>ddlDepartamento control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartamento;

        /// <summary>txtMunicipio control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMunicipio;

        /// <summary>txtTitular control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitular;

        /// <summary>btnGuardar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>btnCancelar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>phCuenta control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCuenta;

        /// <summary>txtLogin control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtLogin;

        /// <summary>txtCorreo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;

        /// <summary>txtClave control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtClave;

        /// <summary>btnCrearCuenta control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCrearCuenta;

        /// <summary>btnCancelarCuenta control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelarCuenta;

        /// <summary>phEstado control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEstado;

        /// <summary>txtMotivo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivo;

        /// <summary>btnConfirmarEstado control.</summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarEstado;

        /// <summary>btnCancelarEstado control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelarEstado;

        /// <summary>ddlFiltroCampana control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroCampana;

        /// <summary>btnFiltrar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>btnNuevo control.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>phLista control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        /// <summary>rptCandidatos control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptCandidatos;

        /// <summary>phVacio control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
