//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{


    public partial class CargosPagina
    {

        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        protected global::System.Web.UI.WebControls.PlaceHolder phForm;

        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        protected global::System.Web.UI.WebControls.DropDownList ddlNivel;

        protected global::System.Web.UI.WebControls.TextBox txtOrden;

        protected global::System.Web.UI.WebControls.Button btnGuardar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;

        protected global::System.Web.UI.WebControls.PlaceHolder phEstado;

        protected global::System.Web.UI.WebControls.TextBox txtMotivo;

        protected global::System.Web.UI.WebControls.Button btnConfirmarEstado;

        protected global::System.Web.UI.WebControls.Button btnCancelarEstado;

        protected global::System.Web.UI.WebControls.Button btnNuevo;

        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        protected global::System.Web.UI.WebControls.Repeater rptCargos;

        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
