//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{
    public partial class EncuestasPagina
    {
        /// <summary>
        /// phMensaje control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        /// <summary>
        /// phForm control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phForm;

        /// <summary>
        /// ddlCampana control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCampana;

        /// <summary>
        /// txtPregunta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPregunta;

        /// <summary>
        /// txtDescripcion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        /// <summary>
        /// txtOpciones control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtOpciones;

        /// <summary>
        /// phOpcionesBloqueadas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phOpcionesBloqueadas;

        /// <summary>
        /// txtInicio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtInicio;

        /// <summary>
        /// txtCierre control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCierre;

        /// <summary>
        /// ddlCategoria control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;

        /// <summary>
        /// btnGuardar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>
        /// btnCancelar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>
        /// phEstado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEstado;

        /// <summary>
        /// txtMotivo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivo;

        /// <summary>
        /// btnConfirmarEstado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarEstado;

        /// <summary>
        /// btnCancelarEstado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancelarEstado;

        /// <summary>
        /// phResultado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phResultado;

        /// <summary>
        /// rptResultado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptResultado;

        /// <summary>
        /// btnCerrarResultado control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCerrarResultado;

        /// <summary>
        /// btnNueva control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNueva;

        /// <summary>
        /// phLista control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        /// <summary>
        /// rptEncuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptEncuestas;

        /// <summary>
        /// phVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
