//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{
    public partial class Moderacion
    {
        /// <summary>phMensaje control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        /// <summary>phDecision control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phDecision;

        /// <summary>phAvisoRetiro control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAvisoRetiro;

        /// <summary>txtMotivo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivo;

        /// <summary>btnConfirmar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmar;

        /// <summary>btnCancelar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>ddlEstado control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>btnFiltrar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>phLista control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        /// <summary>rptPublicaciones control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptPublicaciones;

        /// <summary>phVacio control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
