//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{
    public partial class ModulosPagina
    {
        /// <summary>phMensaje control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        /// <summary>phDecision control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phDecision;

        /// <summary>phMotivo control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMotivo;

        /// <summary>txtMotivo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivo;

        /// <summary>btnConfirmar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmar;

        /// <summary>btnCancelar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>rptGrupos control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptGrupos;
    }
}
