//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{


    public partial class PadronPagina
    {

        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        protected global::System.Web.UI.WebControls.PlaceHolder phAbierto;

        protected global::System.Web.UI.WebControls.PlaceHolder phCarga;

        protected global::System.Web.UI.WebControls.TextBox txtCorreos;

        protected global::System.Web.UI.WebControls.Button btnCargar;

        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        protected global::System.Web.UI.WebControls.Repeater rptMiembros;

        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
