//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{
    public partial class Partidos
    {
        /// <summary>phMensaje control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        /// <summary>phForm control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phForm;

        /// <summary>txtNombre control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>txtSiglas control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSiglas;

        /// <summary>txtDescripcion control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        /// <summary>btnGuardar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>btnCancelar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>phEstado control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEstado;

        /// <summary>txtMotivo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivo;

        /// <summary>btnConfirmarEstado control.</summary>
        protected global::System.Web.UI.WebControls.Button btnConfirmarEstado;

        /// <summary>btnCancelarEstado control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelarEstado;

        /// <summary>btnNuevo control.</summary>
        protected global::System.Web.UI.WebControls.Button btnNuevo;

        /// <summary>phLista control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        /// <summary>rptPartidos control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptPartidos;

        /// <summary>phVacio control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
