//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{


    public partial class SolicitudesPagina
    {

        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        protected global::System.Web.UI.WebControls.PlaceHolder phDescartar;

        protected global::System.Web.UI.WebControls.TextBox txtNotas;

        protected global::System.Web.UI.WebControls.Button btnDescartar;

        protected global::System.Web.UI.WebControls.Button btnCancelar;

        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        protected global::System.Web.UI.WebControls.Repeater rptSolicitudes;

        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
