//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Admin
{
    public partial class Verificacion
    {
        /// <summary>phMensaje control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        /// <summary>phDecision control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phDecision;

        /// <summary>ddlNivel control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlNivel;

        /// <summary>txtMotivo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotivo;

        /// <summary>btnGuardar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnGuardar;

        /// <summary>btnCancelar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnCancelar;

        /// <summary>ddlTipo control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;

        /// <summary>ddlPendientes control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPendientes;

        /// <summary>btnFiltrar control.</summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>phLista control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;

        /// <summary>rptBandeja control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptBandeja;

        /// <summary>phVacio control.</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
