//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Controles
{
    public partial class Comentarios
    {
        /// <summary>
        /// phFormulario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phFormulario;

        /// <summary>
        /// txtComentario control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtComentario;

        /// <summary>
        /// btnPublicar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPublicar;

        /// <summary>
        /// phInvitacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phInvitacion;

        /// <summary>
        /// phMensaje control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        /// <summary>
        /// litMensaje control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>
        /// rptComentarios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptComentarios;

        /// <summary>
        /// phVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
