//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend.Controles
{
    public partial class Interaccion
    {
        /// <summary>
        /// lnkMeGusta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkMeGusta;

        /// <summary>
        /// lnkNoMeGusta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkNoMeGusta;

        /// <summary>
        /// lnkComentar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkComentar;

        /// <summary>
        /// lnkComentarEnlace control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkComentarEnlace;

        /// <summary>
        /// phApoyo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phApoyo;

        /// <summary>
        /// phAviso control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAviso;

        /// <summary>
        /// litAviso control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAviso;
    }
}
