//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class Acceso
    {
        /// <summary>
        /// phError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// txtCorreo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;

        /// <summary>
        /// txtClave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClave;

        /// <summary>
        /// chkRecordar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkRecordar;

        /// <summary>
        /// btnEntrar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnEntrar;
    }
}
