//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class AnaliticaPagina
    {
        /// <summary>
        /// ddlCampana control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCampana;

        /// <summary>
        /// ddlCategoria control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;

        /// <summary>
        /// ddlPartido control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPartido;

        /// <summary>
        /// ddlDepartamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartamento;

        /// <summary>
        /// ddlNivel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlNivel;

        /// <summary>
        /// txtDesde control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDesde;

        /// <summary>
        /// txtHasta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHasta;

        /// <summary>
        /// btnActualizar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnActualizar;

        /// <summary>
        /// rptFichas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFichas;

        /// <summary>
        /// btnLimpiar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLimpiar;

        /// <summary>
        /// phError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phError;

        /// <summary>
        /// phVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;

        /// <summary>
        /// phTablero control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phTablero;

        /// <summary>
        /// rptKpis control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptKpis;

        /// <summary>
        /// rptHallazgos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptHallazgos;

        /// <summary>
        /// phSinHallazgos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSinHallazgos;

        /// <summary>
        /// rptOferta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptOferta;

        /// <summary>
        /// rptOfertaTabla control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptOfertaTabla;

        /// <summary>
        /// litPilaEstados control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litPilaEstados;

        /// <summary>
        /// rptEstados control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptEstados;

        /// <summary>
        /// rptPartidos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPartidos;

        /// <summary>
        /// rptDensidad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDensidad;

        /// <summary>
        /// rptPartidosTabla control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPartidosTabla;

        /// <summary>
        /// litDona control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litDona;

        /// <summary>
        /// rptParticipacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptParticipacion;

        /// <summary>
        /// rptParticipacionTabla control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptParticipacionTabla;

        /// <summary>
        /// rptRanking control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRanking;

        /// <summary>
        /// rptRankingTabla control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRankingTabla;

        /// <summary>
        /// litActividad control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litActividad;

        /// <summary>
        /// rptTerritorio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptTerritorio;

        /// <summary>
        /// rptTerritorioTabla control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptTerritorioTabla;

        /// <summary>
        /// rptVerificacion control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptVerificacion;

        /// <summary>
        /// rptSugerencias control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSugerencias;

        /// <summary>
        /// phAvisoOculto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAvisoOculto;

        /// <summary>
        /// grafKpi control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafKpi;

        /// <summary>
        /// grafHallazgos control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafHallazgos;

        /// <summary>
        /// grafBrecha control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafBrecha;

        /// <summary>
        /// grafEstados control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafEstados;

        /// <summary>
        /// grafPartidos control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafPartidos;

        /// <summary>
        /// grafDensidad control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafDensidad;

        /// <summary>
        /// grafSigno control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafSigno;

        /// <summary>
        /// grafTipos control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafTipos;

        /// <summary>
        /// grafRanking control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafRanking;

        /// <summary>
        /// grafActividad control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafActividad;

        /// <summary>
        /// grafTerritorio control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafTerritorio;

        /// <summary>
        /// grafVerificacion control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafVerificacion;

        /// <summary>
        /// grafAsistente control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl grafAsistente;
    }
}
