//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class CampanaPagina
    {
        /// <summary>
        /// phFeed control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phFeed;

        /// <summary>
        /// rptFeed control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFeed;

        /// <summary>
        /// phFeedVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phFeedVacio;

        /// <summary>
        /// rptCategorias control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCategorias;

        /// <summary>
        /// rptRail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRail;

        /// <summary>
        /// phCandidatos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCandidatos;

        /// <summary>
        /// rptCandidatos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCandidatos;

        /// <summary>
        /// phCandidatosVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCandidatosVacio;

        /// <summary>
        /// phPropuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phPropuestas;

        /// <summary>
        /// rptPropuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPropuestas;

        /// <summary>
        /// phPropuestasVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phPropuestasVacio;

        /// <summary>
        /// phInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phInfo;
    }
}
