//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class Campanas
    {
        /// <summary>
        /// rptActivas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptActivas;

        /// <summary>
        /// rptProximas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptProximas;

        /// <summary>
        /// rptCerradas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCerradas;

        /// <summary>
        /// phVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
