//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class CandidatoPagina
    {
        /// <summary>
        /// phPropuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phPropuestas;

        /// <summary>
        /// rptPropuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPropuestas;

        /// <summary>
        /// phPropuestasVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phPropuestasVacio;

        /// <summary>
        /// phPublicaciones control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phPublicaciones;

        /// <summary>
        /// rptPublicaciones control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPublicaciones;

        /// <summary>
        /// phPublicacionesVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phPublicacionesVacio;

        /// <summary>
        /// interPerfil control.
        /// </summary>
        protected global::frontend.Controles.Interaccion interPerfil;

        /// <summary>
        /// phOpiniones control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phOpiniones;

        /// <summary>
        /// comentsPerfil control.
        /// </summary>
        protected global::frontend.Controles.Comentarios comentsPerfil;

        /// <summary>
        /// phInfo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phInfo;

        /// <summary>
        /// phContacto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phContacto;

        /// <summary>
        /// phCorreo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCorreo;

        /// <summary>
        /// phTelefono control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phTelefono;

        /// <summary>
        /// phSitio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSitio;

        /// <summary>
        /// phRedes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phRedes;

        /// <summary>
        /// rptRedes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptRedes;
    }
}
