//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class CandidatosPagina
    {
        /// <summary>
        /// txtBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>
        /// ddlCampana control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCampana;

        /// <summary>
        /// ddlNivel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlNivel;

        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>
        /// rptCandidatos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCandidatos;

        /// <summary>
        /// phVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
