//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class Confirmar
    {
        /// <summary>
        /// litTitulo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTitulo;

        /// <summary>
        /// litMensaje control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMensaje;

        /// <summary>
        /// phSeguir control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSeguir;

        /// <summary>
        /// phEntrar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEntrar;
    }
}
