//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class _Default
    {
        /// <summary>
        /// txtBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>
        /// btnBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>
        /// phActual control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phActual;

        /// <summary>
        /// phEncuesta control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEncuesta;

        /// <summary>
        /// tarjetaEncuesta control.
        /// </summary>
        protected global::frontend.Controles.EncuestaCard tarjetaEncuesta;

        /// <summary>
        /// rptCandidatos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCandidatos;

        /// <summary>
        /// rptCampanas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCampanas;
    }
}
