//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class _Default
    {
        /// <summary>
        /// txtBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>
        /// btnBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>
        /// phActual control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phActual;

        /// <summary>
        /// phEncuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEncuestas;

        /// <summary>
        /// zonaEncuestas control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl zonaEncuestas;

        /// <summary>
        /// rptEncuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptEncuestas;

        /// <summary>
        /// phVerMas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVerMas;

        /// <summary>
        /// hdnEncuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnEncuestas;

        /// <summary>
        /// phIniciativas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phIniciativas;

        /// <summary>
        /// phProponer control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phProponer;

        /// <summary>
        /// phIniciativasOcultas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phIniciativasOcultas;

        /// <summary>
        /// zonaIniciativas control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl zonaIniciativas;

        /// <summary>
        /// rptIniciativas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptIniciativas;

        /// <summary>
        /// phVerMasInic control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVerMasInic;

        /// <summary>
        /// hdnIniciativas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnIniciativas;

        /// <summary>
        /// rptCandidatos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCandidatos;

        /// <summary>
        /// rptCampanas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCampanas;
    }
}
