//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class MiCuenta
    {
        protected global::System.Web.UI.WebControls.PlaceHolder phConfirmada;
        protected global::System.Web.UI.WebControls.PlaceHolder phPendiente;
        protected global::System.Web.UI.WebControls.PlaceHolder phCerrado;
        protected global::System.Web.UI.WebControls.PlaceHolder phFormulario;
        protected global::System.Web.UI.WebControls.PlaceHolder phOk;
        protected global::System.Web.UI.WebControls.Literal litOk;
        protected global::System.Web.UI.WebControls.PlaceHolder phError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.TextBox txtTitulo;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartamento;
        protected global::System.Web.UI.WebControls.LinkButton lnkCancelar;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.HiddenField hdnId;
        protected global::System.Web.UI.WebControls.Literal litResumen;
        protected global::System.Web.UI.WebControls.PlaceHolder phAvisoLista;
        protected global::System.Web.UI.WebControls.Literal litAvisoLista;
        protected global::System.Web.UI.WebControls.PlaceHolder phSinIniciativas;
        protected global::System.Web.UI.WebControls.Repeater rptMias;
    }
}
