//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{


    public partial class OrganizacionesPagina
    {

        protected global::System.Web.UI.WebControls.HyperLink lnkDemo;

        protected global::System.Web.UI.WebControls.PlaceHolder phPlanes;

        protected global::System.Web.UI.WebControls.Repeater rptPlanes;

        protected global::System.Web.UI.WebControls.PlaceHolder phSinPlanes;

        protected global::System.Web.UI.WebControls.PlaceHolder phMensaje;

        protected global::System.Web.UI.WebControls.PlaceHolder phForm;

        protected global::System.Web.UI.WebControls.TextBox txtOrganizacion;

        protected global::System.Web.UI.WebControls.TextBox txtContacto;

        protected global::System.Web.UI.WebControls.TextBox txtCorreo;

        protected global::System.Web.UI.WebControls.TextBox txtTelefono;

        protected global::System.Web.UI.WebControls.DropDownList ddlPlan;

        protected global::System.Web.UI.WebControls.TextBox txtFecha;

        protected global::System.Web.UI.WebControls.TextBox txtProceso;

        protected global::System.Web.UI.WebControls.TextBox txtMensaje;

        protected global::System.Web.UI.WebControls.TextBox txtSitio;

        protected global::System.Web.UI.WebControls.Button btnEnviar;
    }
}
