//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class PartidoPagina
    {
        /// <summary>
        /// interPartido control.
        /// </summary>
        protected global::frontend.Controles.Interaccion interPartido;

        /// <summary>
        /// rptCandidatos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCandidatos;

        /// <summary>
        /// phSinCandidatos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phSinCandidatos;

        /// <summary>
        /// comentsPartido control.
        /// </summary>
        protected global::frontend.Controles.Comentarios comentsPartido;
    }
}
