//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class PropuestasPagina
    {
        /// <summary>
        /// txtBuscar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>
        /// ddlCategoria control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;

        /// <summary>
        /// ddlCampana control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCampana;

        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;

        /// <summary>
        /// rptPropuestas control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPropuestas;

        /// <summary>
        /// phVacio control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
    }
}
