//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class PropuestaPagina
    {
        /// <summary>
        /// interPropuesta control.
        /// </summary>
        protected global::frontend.Controles.Interaccion interPropuesta;

        /// <summary>
        /// comentsPropuesta control.
        /// </summary>
        protected global::frontend.Controles.Comentarios comentsPropuesta;

        /// <summary>
        /// phAdicional control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAdicional;

        /// <summary>
        /// phAutor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phAutor;
    }
}
