//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class Registro
    {
        /// <summary>
        /// rptBeneficios control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptBeneficios;

        /// <summary>
        /// phError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phError;

        /// <summary>
        /// litError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litError;

        /// <summary>
        /// txtNombres control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombres;

        /// <summary>
        /// txtApellidos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtApellidos;

        /// <summary>
        /// txtCorreo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;

        /// <summary>
        /// txtClave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClave;

        /// <summary>
        /// txtClave2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClave2;

        /// <summary>
        /// phCandidato control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phCandidato;

        /// <summary>
        /// ddlCampana control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCampana;

        /// <summary>
        /// ddlCargo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCargo;

        /// <summary>
        /// ddlDepartamento control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartamento;

        /// <summary>
        /// txtPartido control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPartido;

        /// <summary>
        /// chkTerminos control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkTerminos;

        /// <summary>
        /// btnCrear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCrear;
    }
}
