//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontend
{
    public partial class ReporteAsistente
    {
        protected global::System.Web.UI.WebControls.PlaceHolder phElegir;
        protected global::System.Web.UI.WebControls.PlaceHolder phError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.PlaceHolder phLista;
        protected global::System.Web.UI.WebControls.Repeater rptConsultas;
        protected global::System.Web.UI.WebControls.Button btnGenerar;
        protected global::System.Web.UI.WebControls.PlaceHolder phVacio;
        protected global::System.Web.UI.WebControls.PlaceHolder phReporte;
        protected global::System.Web.UI.WebControls.Repeater rptReporte;
    }
}
